name: generate-pdf-from-latex
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate "Discrete Mathematics" PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 00_complete.tex
          working_directory: aleph/discrete
          post_compile: "mv aleph/discrete/00_complete.pdf web/discrete_mathematics.pdf"

      - name: Generate "Mathematical Methods I" PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 00_complete.tex
          working_directory: aleph/methods
          post_compile: "mv aleph/methods/00_complete.pdf web/mathematical_methods.pdf"

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
