name: generate-pdf-from-latex
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate "Discrete Mathematics" PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 00_complete.tex
          working_directory: aleph/discrete
          post_compile: "mv 00_complete.pdf ../../web/discrete_mathematics.pdf"

      - name: Generate "Mathematical Methods I" PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 00_complete.tex
          working_directory: aleph/methods
          post_compile: "mv 00_complete.pdf ../../web/mathematical_methods.pdf"
      - run: touch web/.nojekyll
      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: web
          ssh-key: ${{ secrets.Actions }}
          single-commit: true
